name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
   
    runs-on: ${{ matrix.os }}  # Use matrix variable for OS
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Define OS options

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify Node.js version

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Run Playwright Tests
        run: npx playwright test  # Run your Playwright tests

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/  # Specify path to your report directory
